data <- read.table("household_power_consumption.txt", header= TRUE, sep= ";", stringsAsFactors = FALSE)
head(data)
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
classes<- sapply(data, class)
classes
data_2007 <- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data) 
datetime <- strptime(paste(data_2007$Date, data_2007$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
globalActivePower <- as.numeric(data_2007$Global_active_power)
subMetering1 <- as.numeric(data_2007$Sub_metering_1)
subMetering2 <- as.numeric(data_2007$Sub_metering_2)
subMetering3 <- as.numeric(data_2007$Sub_metering_3)
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),cex=0.7)
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()
