data <- read.table("household_power_consumption.txt", header= TRUE, sep= ";", stringsAsFactors = FALSE)
head(data)
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
classes<- sapply(data, class)
classes
data_2007 <- subset(data, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data) 
datetime <- strptime(paste(data_2007$Date, data_2007$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
globalActivePower <- as.numeric(data_2007$Global_active_power)
globalReactivePower <- as.numeric(data_2007$Global_reactive_power)
voltage <- as.numeric(data_2007$Voltage)
subMetering1 <- as.numeric(data_2007$Sub_metering_1)
subMetering2 <- as.numeric(data_2007$Sub_metering_2)
subMetering3 <- as.numeric(data_2007$Sub_metering_3)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power")
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o",cex=0.2)
plot(datetime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", height=480, width=480)
dev.off()
